version: '1.0.{build}'

before_build:
- appveyor-retry dotnet restore -v Minimal
- choco install opencover.portable
- choco install codecov

artifacts:
- path: '**\*.nupkg'
  name: AllNugetPackages

deploy:
  provider: NuGet
  api_key:
    secure: eaxBOBHGynI8k6n13m7sjFDbbm3t8r8zUhhXeEnPKxWAqz31GIUO1mLbHW2k9kT1
  skip_symbols: true
  artifact: /.*\.nupkg/

build_script:
- dotnet build
- dotnet test

test_script:
- OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -output:"coverage.xml" -oldstyle
- codecov -f "coverage.xml"