version: '1.0.{build}'
configuration:
- Release
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN:
         secure: MBnad/ilkq6FC4o95aE/cHDTOOGwcBIY/MPprWF/WpyePD34GS/MHIIf4j0CxseI

before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build
test_script:
- dotnet test

after_test:
# generate report for NUnit testing framework:
#    -cmd: packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single YOURPROJECT.Tests\bin\debug\YOURPROJECT.Tests.dll" -output:coverage.xml

# generate report for MSTest testing framework:
- cmd: packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -output:"MyProject_coverage.xml" -oldstyle
#packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover ".\MyProject_coverage.xml" -r %COVERALLS_REPO_TOKEN%
