version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Test
          command: dotnet test
      - run:
          name: InstallCoveralls
          command: choco install opencover.portable
      - run:
          name: InstallCodecov
          command: choco install codecov
      - run:
          name: CreateCoveralls
          command: OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -output:".\MyProject_coverage.xml" -oldstyle
      - run:
          name: SendCoverFiles
          command: csmacnz.Coveralls --opencover -i .\MyProject_coverage.xml --repoToken VPxb8MmhXS0IAh4L8qLoPmnRebvb1aoYF